### PR TITLE
fix(adapter-commons): Add missing overloads

### PR DESCRIPTION
**Pull request by vonagam**
[#1838](https://github.com/feathersjs/feathers/pull/1838) added some overloads that were added in [#1567](https://github.com/feathersjs/feathers/pull/1567) and then removed in [#1620](https://github.com/feathersjs/feathers/pull/1620). The problem is that not all of them were put back. Those are missing:

```ts
create (data: Partial<T> | Array<Partial<T>>, params?: Params): Promise<T | T[]>;
patch (id: NullableId, data: Partial<T>, params?: Params): Promise<T | T[]>;
remove (id: NullableId, params?: Params): Promise<T | T[]>;
```

Simple demonstration ([typescript playground link](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=12&pc=83#code/MYGwhgzhAEBiD29oG8BQ0PQEZgE4AoBLAEwC5oA7AVwFssBTXASnOrsfUxwJNapBAtK-EJwwB6cdjxEyw9rmgAfYQKFsGildQFjpPORsbLVglHszRc9AC5VcFaCQDcegL6oPqYPAoQb0ABmiNAAvJT0AO5wiPhMrj5+ASRh0ADMACzQkPKaJjogCb7+VvQQ-AHhwfAAdNyy8dCS0DYAFoQwIIQU9NCRhALQAA648MRUwL2Mo4r9bfBUAW2EuMTQ8ABujCDwYMRAA)), why you need them:

```ts
class Foo {
    bar(id: number): number
    bar(id: null): null
    // bar(id: number | null): number | null
    bar(id: number | null) {
        return id;
    }
}

const foo = new Foo();
const id = 34 as number | null;
const result = foo.bar(id); // this line will produce error without third overload
```

### CODE REVIEW

**Comment by daffl** [comment]
Great, thanks for submitting this here! I kind of messed up a previous merge so this may have to become part of the 5.x prerelease. This means we can also get any breaking changes in and start testing it out (it's now at least running against `feathers-memory` and I'm looking into moving some of the other ones over).

I'm also slowly working on finalizing the Feathers core migration to TypeScript and I'm thinking that types like `Paginated` should also live in the adapter commons since it doesn't have much to do with Feathers core services.

**Comment by vonagam** [comment]
If it will go into 5, then `Promise<T>` can be removed from return type of [`_find`](https://github.com/feathersjs/databases/blob/c67e051e18def321466d1b459c15cd145f03aa46/packages/adapter-commons/src/service.ts#L32) in `InternalServiceMethods` of `InternalServiceMethods`. It was small breaking change that caused partial reversion of original PR.

Yes, moving [`Paginated<T>`](https://github.com/feathersjs/feathers/blob/44c183cb0ffc156309f3189f8dd66e39fecc75c8/packages/feathers/index.d.ts#L44), [`PaginationOptions`](https://github.com/feathersjs/feathers/blob/44c183cb0ffc156309f3189f8dd66e39fecc75c8/packages/feathers/index.d.ts#L26), [`Params.paginate`](https://github.com/feathersjs/feathers/blob/44c183cb0ffc156309f3189f8dd66e39fecc75c8/packages/feathers/index.d.ts#L36) into `adapter-commons` seems like a reasonable idea.

Also does anybody uses type [`ClientSideParams`](https://github.com/feathersjs/feathers/blob/44c183cb0ffc156309f3189f8dd66e39fecc75c8/packages/feathers/index.d.ts#L31)? If yes, then `ClientSideParams.paginate` should be moved here too and also, shouldn't `headers` and `route` be a part of client side params?

**Comment by deskoh** [comment]
@vonagam @daffl 
I refer to the example [here](https://docs.feathersjs.com/guides/basics/services.html#customizing-a-service).

Somehow TypeScript is having issues with the current typings.

See the simplified repro of the issue in [TypeScript Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCJzHZBvAUMg5GYCAGwBMBGALmRAFcBbAI2gG59DizyAmWgM5gooAOYcAvrlwJScAQOQAxAPYqcnAszhQAFMHK10mAJRGMcTcm16D5zAG0AumbQXnVm-sNvMyAD6+cM6uxliBYc4ahDHIUBBg9FAgyAYcMVJSMnIKyACyAJ6q6hAAHpAg5IrF0YRedkEBQSH24c1OtbFxCUkpaVaZQA)

Any ideas how to resolve this?

**Comment by daffl** [comment]
Published a patch version with this PR reverted since it breaks even the tutorial.

**Comment by vonagam** [comment]
When you extend and override an overloaded method you have to repeat overloads in subclass during overriding (so the playground becomes [this](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCJzHZBvAUMg5GYCAGwBMBGALmRAFcBbAI2gG59DizyAmWgM5gooAOYcAvrlwJScAQOQAxAPYqcnAszhQAFMHK10mAJRGMcTcm16D5zAG0AumbQXnVm-sNvMyAD6+cM6uxliBYc4ahDHIUBBg9FAgyAYcMVJSMnIKyACyAJ6q6hAAHpAg5IrF0YRedkGhFp463vbBLu0eMfU+YQFBIe0DkU61sXEJSSlpVplAA)).

But during extending `AdapterService` you are not supposed to overwrite those overloaded methods, you are supposed to provide implementations for underscore counterparts - so `_find` instead of `find`.

Note: you reverted not this PR, but #9 (which is about overloads too). And seems like you will need to do a reversal of that  reversal.

**Comment by daffl** [comment]
That is correct, thank you. It's been reverted to the original state now. If would be appreciated if someone could submit a follow-up PR for the next breaking release or an issue to keep track of this.

**Pull request merged**
